### PR TITLE
Changed dependency for email validation.

### LINKED ISSUE #2: check if email domain exist
Maybe with a ping

### PR DESCRIPTION
**Pull request by triptu**
This fixes #2.

### CODE REVIEW

**Comment by Mte90** [comment]
As I written here https://github.com/CodeAtCode/CSVEmailVerifier/issues/2#issuecomment-251810640 this module have the same features?

**Comment by triptu** [comment]
Sorry for that inconvenience. I am new to github and open source and got confused between pull request and commits.

**Comment by triptu** [comment]
You can merge the pull request now if there is nothing else I need to work on.

**Comment by Mte90** [comment]
As I written here https://github.com/CodeAtCode/CSVEmailVerifier/issues/2#issuecomment-251810640 I need a comparison between the two module to see what we lost in case we changed the module.

**Comment by triptu** [comment]
I have looked upon the source of both the modules. 

#### What we lose:-

emailahoy uses a SMTP connection while email-validator doesn't. We will lose this feature. But it is a good thing in my opinion because it's not reliable. Reason is explained in more detail in email-validator's readme.

#### What we gain :-
- email-validator can recognize internationalized domain names like this example@良好mail.中国. 
- It also checks for the A and AAA record along with mx record. So you you can be completely sure if the email is invalid. More ever the mx record method in emailahoy is not reliable. In my system it failed to give the expected result even for gmail.
-  It is a well updated package and not outdated.
- email-validator gives more associated details in a nice format which can be helpful in future for any expansion of this project.

**Comment by Mte90** [comment]
you convinced me :-D

**Pull request merged**
